version: "3.8"

services:
  app:
    build: .
    container_name: tiktk_ui
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - DATA_URL = 0
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: tiktk_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://mongo:27017/test
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
